name: Node.js CI

on:
  push:
    branches: [ "master", "alpha" ]
  pull_request:
    branches: [ "master", "alpha" ]
    
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci --if-present
    - run: npm run build --if-present
    - run: npm test --if-present
    - run: npx semantic-release
